name: Deploy to Server

on:
  push:
    branches:
      - main  # Деплой будет происходить только при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build project
        run: |
          # Вставьте команду сборки вашего проекта, например:
          npm install
          npm run build

      - name: Deploy to server
        env:
          SERVER_HOST: 176.114.89.169
          SERVER_USER: root
          DEPLOY_DIR: /var/www/ # Укажите директорию на сервере, куда будет копироваться сборка
        run: |
          # Создание директории на сервере, если её нет
          ssh $SERVER_USER@$SERVER_HOST "mkdir -p $DEPLOY_DIR"
          # Копирование файлов на сервер
          rsync -avz --delete dist/ $SERVER_USER@$SERVER_HOST:$DEPLOY_DIR
